/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Facets
         * @description Counties, utilities, and modeled outcomes available for filtering.
         */
        get: operations["facets_api_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness check used by the deploy smoke test and the frontend banner.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-output/{region_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Output
         * @description Stored offline regression outputs. Nothing is fit or scored per request.
         */
        get: operations["get_model_output_api_model_output__region_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regions */
        get: operations["list_regions_api_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/{region_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Region
         * @description Region metadata, every metric observation, missing categories, and geometry.
         */
        get: operations["get_region_api_regions__region_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/{region_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Region Evidence */
        get: operations["get_region_evidence_api_regions__region_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/{region_id}/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Region Summaries
         * @description Which summary categories have a stored summary for this region.
         */
        get: operations["list_region_summaries_api_regions__region_id__summaries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Screening
         * @description Regions flagged as priorities, ranked by agreement across specifications.
         *
         *     DER outcomes flag adoption below prediction (residual at or below the 25th
         *     percentile); burden outcomes flag burden above prediction (75th or higher).
         */
        get: operations["screening_api_screening_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Summary
         * @description Return the stored, evidence-grounded summary for a region and category.
         *
         *     Summaries are generated offline; this endpoint never calls an LLM. When no
         *     traceable summary exists, status is "unavailable" and the retrieved evidence
         *     is returned with the reason in `warnings`.
         */
        post: operations["request_summary_api_summaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary Categories
         * @description Valid summary categories and their display labels.
         */
        get: operations["summary_categories_api_summary_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompareMetricRow */
        CompareMetricRow: {
            /** Display Values */
            display_values: {
                [key: string]: string | null;
            };
            /** Metric Category */
            metric_category: string | null;
            /** Metric Name */
            metric_name: string;
            /** Metric Unit */
            metric_unit: string | null;
            /** Values */
            values: {
                [key: string]: number | null;
            };
        };
        /** CompareModelRow */
        CompareModelRow: {
            /** Model Version */
            model_version: string;
            /** Outcome Name */
            outcome_name: string;
            /** Priority Flag */
            priority_flag: {
                [key: string]: boolean | null;
            };
            /** Residual Percentile */
            residual_percentile: {
                [key: string]: number | null;
            };
        };
        /** CompareResponse */
        CompareResponse: {
            /** Metrics */
            metrics: components["schemas"]["CompareMetricRow"][];
            /** Model Outputs */
            model_outputs: components["schemas"]["CompareModelRow"][];
            /** Overviews */
            overviews: {
                [key: string]: components["schemas"]["SummaryResponse"];
            };
            /** Region Ids */
            region_ids: string[];
            /** Regions */
            regions: components["schemas"]["Region"][];
        };
        /** Evidence */
        Evidence: {
            /** Evidence Id */
            evidence_id: number;
            /** Evidence Text */
            evidence_text: string;
            /** Evidence Type */
            evidence_type: string | null;
            /** Region Id */
            region_id: string | null;
            /** Source Name */
            source_name: string | null;
            /** Source Url */
            source_url: string | null;
        };
        /** FacetCount */
        FacetCount: {
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** Facets */
        Facets: {
            /** Counties */
            counties: components["schemas"]["FacetCount"][];
            /**
             * Outcomes
             * @description Outcomes with stored model outputs.
             */
            outcomes: components["schemas"]["FacetCount"][];
            /** Utilities */
            utilities: components["schemas"]["FacetCount"][];
        };
        /** Geometry */
        Geometry: {
            /** Crs */
            crs: string | null;
            /** Geometry Format */
            geometry_format: string;
            /** Geometry Wkt */
            geometry_wkt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @description Database file name (never a full server path).
             */
            database?: string | null;
            /** Message */
            message: string;
            /** Setup Command */
            setup_command?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /**
             * Synthetic
             * @description True when serving the synthetic fixture database.
             * @default false
             */
            synthetic: boolean;
        };
        /** Metric */
        Metric: {
            /**
             * Display Value
             * @description Human-readable value with units.
             */
            display_value: string;
            /** Metric Category */
            metric_category: string | null;
            /** Metric Name */
            metric_name: string;
            /** Metric Unit */
            metric_unit: string | null;
            /** Metric Value */
            metric_value: number;
            /** Observed At */
            observed_at: string | null;
            /** Source Name */
            source_name: string | null;
        };
        /** ModelOutput */
        ModelOutput: {
            /** Actual Value */
            actual_value: number | null;
            /** Assumptions */
            assumptions: string | null;
            /** Generated At */
            generated_at: string | null;
            /** Model Output Id */
            model_output_id: number;
            /** Model Version */
            model_version: string;
            /** Outcome Name */
            outcome_name: string;
            /** Predicted Value */
            predicted_value: number | null;
            /**
             * Priority Flag
             * @description DER outcomes: residual at or below the 25th percentile. Affordability outcomes: at or above the 75th percentile.
             */
            priority_flag: boolean | null;
            /**
             * Residual Percentile
             * @description Rank of the residual within the fitted sample, 0 to 1.
             */
            residual_percentile: number | null;
            /** Residual Value */
            residual_value: number | null;
        };
        /** ModelOutputList */
        ModelOutputList: {
            /** Items */
            items: components["schemas"]["ModelOutput"][];
            /** Region Id */
            region_id: string;
        };
        /** Region */
        Region: {
            /** County */
            county: string | null;
            /**
             * Region Id
             * @description Five-character ZCTA, the stable key across every table.
             */
            region_id: string;
            /** Region Name */
            region_name: string | null;
            /** Region Type */
            region_type: string;
            /** State */
            state: string | null;
            utility: components["schemas"]["Utility"] | null;
        };
        /** RegionDetail */
        RegionDetail: {
            geometry: components["schemas"]["Geometry"] | null;
            /** Metrics */
            metrics: components["schemas"]["Metric"][];
            /**
             * Missing Metric Categories
             * @description Metric categories with no observation for this region.
             */
            missing_metric_categories: string[];
            region: components["schemas"]["Region"];
        };
        /** RegionList */
        RegionList: {
            /** Items */
            items: components["schemas"]["Region"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Matching regions before limit/offset.
             */
            total: number;
        };
        /** ScreeningResponse */
        ScreeningResponse: {
            /**
             * Direction
             * @description Which residuals the priority flag marks for this outcome.
             * @enum {string}
             */
            direction: "low" | "high" | "absolute";
            /** Items */
            items: components["schemas"]["ScreeningRow"][];
            /** Outcome Name */
            outcome_name: string;
            /**
             * Total
             * @description Regions with at least one flagged specification.
             */
            total: number;
        };
        /** ScreeningRow */
        ScreeningRow: {
            /** Flagged Count */
            flagged_count: number;
            /** Mean Residual Percentile */
            mean_residual_percentile: number | null;
            region: components["schemas"]["Region"];
            /** Specification Count */
            specification_count: number;
        };
        /** SummaryCategory */
        SummaryCategory: {
            /** Category */
            category: string;
            /** Evidence Count */
            evidence_count: number;
            /** Generated At */
            generated_at: string | null;
            /** Model Version */
            model_version: string | null;
            /** Summary Id */
            summary_id: number;
        };
        /** SummaryCategoryList */
        SummaryCategoryList: {
            /** Items */
            items: components["schemas"]["SummaryCategory"][];
            /** Region Id */
            region_id: string;
        };
        /** SummaryRequest */
        SummaryRequest: {
            /**
             * Category
             * @default overview
             * @example overview
             * @example observed_der
             * @example model_pv
             */
            category: string;
            /**
             * Region Id
             * @example 90001
             */
            region_id: string;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Category */
            category: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Evidence Ids */
            evidence_ids: number[];
            /** Generated At */
            generated_at: string | null;
            /** Metric Snapshot */
            metric_snapshot: {
                [key: string]: unknown;
            } | null;
            /** Model Version */
            model_version: string | null;
            /** Region Id */
            region_id: string;
            /**
             * Status
             * @description 'available' only when a stored summary exists and every cited evidence record exists and belongs to this region. Otherwise 'unavailable', with the reason and the retrieved evidence still returned.
             * @enum {string}
             */
            status: "available" | "unavailable";
            /** Summary Id */
            summary_id: number | null;
            /** Summary Text */
            summary_text: string | null;
            /**
             * Warnings
             * @description Caveats a reader must see with the summary.
             */
            warnings: string[];
        };
        /** Utility */
        Utility: {
            /** Utility Acronym */
            utility_acronym: string | null;
            /** Utility Id */
            utility_id: number;
            /** Utility Name */
            utility_name: string;
            /** Utility Type */
            utility_type: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_api_compare_get: {
        parameters: {
            query: {
                /** @description Repeat the parameter or pass a comma-separated list. */
                region_ids: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facets_api_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_model_output_api_model_output__region_id__get: {
        parameters: {
            query?: {
                outcome_name?: string | null;
                model_version?: string | null;
            };
            header?: never;
            path: {
                /** @description Five-character ZCTA. */
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOutputList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regions_api_regions_get: {
        parameters: {
            query?: {
                /** @description Prefix of a ZCTA or county, or part of a name. */
                q?: string | null;
                county?: string | null;
                /** @description Utility acronym or full name. */
                utility?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_api_regions__region_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Five-character ZCTA. */
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_evidence_api_regions__region_id__evidence_get: {
        parameters: {
            query?: {
                evidence_type?: string | null;
            };
            header?: never;
            path: {
                /** @description Five-character ZCTA. */
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_region_summaries_api_regions__region_id__summaries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Five-character ZCTA. */
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryCategoryList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screening_api_screening_get: {
        parameters: {
            query?: {
                /** @description Outcome to screen, e.g. y_pv. */
                outcome_name?: string;
                county?: string | null;
                utility?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_summary_api_summaries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_categories_api_summary_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
