#!/usr/bin/env python3
"""Assemble the Zenodo upload bundle for the DER equity dataset.

Collects the processed dataset, the coefficient tables behind the figures, the ACS
housing snapshot and its manifest, the pinned environment files, and the provenance and
metadata documentation into one directory, then writes a SHA-256 manifest over
everything it copied.

Refuses to build if data/processed is missing any file the pipeline is supposed to
write, so a half-built tree cannot be published as a complete release.

Raw third-party inputs are deliberately not included: they are public, cited with
retrieval URLs in SOURCES.md, and downloadable via scripts/fetch_exact_public_data.py.
Redistributing them would add ~2.6 GB and inherit their licensing terms for no gain.

`tracking_the_sun.csv` is excluded by default for the same reason at 927 MB -- it is a
California-filtered copy of LBNL's Tracking the Sun and is regenerated by the
pipeline. Pass --include-tts to bundle it anyway.

    python scripts/make_zenodo_bundle.py                 # build into release/zenodo-bundle
    python scripts/make_zenodo_bundle.py --archive       # also write a .zip beside it
    python scripts/make_zenodo_bundle.py --dry-run       # print the plan and sizes only
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROCESSED = ROOT / "data" / "processed"
RAW_ACS = ROOT / "data" / "raw" / "acs"
STANDARDIZED_TABLES = ROOT / "outputs" / "standardized_tables"
META = ROOT / "release" / "zenodo"
DEFAULT_OUT = ROOT / "release" / "zenodo-bundle"

# Large California-filtered copy of a third-party dataset; regenerated by the pipeline.
EXCLUDED_BY_DEFAULT = {"tracking_the_sun.csv"}

# Written by rebuild_processed_data.py. Bundling whatever happens to be on disk cannot
# tell a complete release from a half-built one, so the absence of any of these is an
# error rather than a quietly smaller bundle.
REQUIRED_PROCESSED = (
    "combined_der_dataset_w_controls_predictors.csv",
    "combined_der_dataset_acs_matched.csv",
    "combined_der_dataset_full.csv",
    "acs_predictors_ca_zip.csv",
    "aggregated_ev_cars.csv",
    "aggregated_ev_chargers.csv",
    "aggregated_power_plant.csv",
    "aggregated_storage.csv",
    "aggregated_wind.csv",
    "ca_zip_ghi_mean_2023.csv",
    "ca_zip_temperature_controls_2023.csv",
    "ca_zip_wind_means_2023.csv",
    "demand.csv",
    "energy_burden.csv",
    "zip_to_utility.csv",
)

# The environment the scripts pin. release/zenodo/README.md tells the reader to run
# `conda env create -f environment.yml`, so the file has to travel with the record.
ENVIRONMENT_FILES = ("environment.yml", "requirements.txt")


def human(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return f"{n:.1f} {unit}" if unit != "B" else f"{n} B"
        n /= 1024
    return f"{n:.1f} GB"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def plan(include_tts: bool, skip_tables: bool = False) -> list[tuple[Path, str]]:
    """Return (source, name-within-bundle) pairs."""
    items: list[tuple[Path, str]] = []

    missing = [n for n in REQUIRED_PROCESSED if not (PROCESSED / n).exists()]
    if missing:
        sys.exit(
            "data/processed is incomplete, so this would publish a partial dataset.\n"
            "Missing:\n" + "".join(f"  {n}\n" for n in missing)
            + "Rebuild it first:  CENSUS_API_KEY=... python scripts/run_all.py --only data"
        )

    for csv in sorted(PROCESSED.glob("*.csv")):
        if csv.name in EXCLUDED_BY_DEFAULT and not include_tts:
            continue
        items.append((csv, f"data/{csv.name}"))

    # Coefficient tables behind every figure. Without them a user has to refit the models
    # before they can redraw anything, which defeats "results can be traced".
    if not skip_tables:
        tables = sorted(STANDARDIZED_TABLES.glob("*.csv"))
        if not tables:
            sys.exit(
                f"no standardized tables found in {STANDARDIZED_TABLES.relative_to(ROOT)}.\n"
                "Rebuild them:  python scripts/run_all.py --only models\n"
                "Or pass --skip-tables to publish the data without them."
            )
        for csv in tables:
            items.append((csv, f"model_outputs/{csv.name}"))

    for name in ENVIRONMENT_FILES:
        src = ROOT / name
        if not src.exists():
            sys.exit(f"missing environment file: {src}")
        items.append((src, name))

    for name in ("acs_2023_5yr_housing_ca_zcta.csv",
                 "acs_2023_5yr_housing_query_manifest.json"):
        src = RAW_ACS / name
        if not src.exists():
            sys.exit(f"missing required ACS provenance file: {src}")
        items.append((src, f"acs_snapshot/{name}"))

    for src, dest in (
        (META / "README.md", "README.md"),
        (META / "zenodo.json", "zenodo.json"),
        (ROOT / "data" / "raw" / "SOURCES.md", "SOURCES.md"),
    ):
        if not src.exists():
            sys.exit(f"missing required documentation file: {src}")
        items.append((src, dest))

    return items


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="bundle directory to create")
    ap.add_argument("--include-tts", action="store_true", help="include the 927 MB tracking_the_sun.csv")
    ap.add_argument("--skip-tables", action="store_true",
                    help="omit outputs/standardized_tables (the coefficient tables behind the figures)")
    ap.add_argument("--archive", action="store_true", help="also write <out>.zip")
    ap.add_argument("--dry-run", action="store_true", help="show what would be bundled, copy nothing")
    args = ap.parse_args()

    items = plan(args.include_tts, skip_tables=args.skip_tables)
    total = sum(src.stat().st_size for src, _ in items)

    print(f"{len(items)} files, {human(total)}")
    if args.include_tts:
        print("  including tracking_the_sun.csv")
    else:
        tts = PROCESSED / "tracking_the_sun.csv"
        if tts.exists():
            print(f"  excluding {tts.name} ({human(tts.stat().st_size)}) -- pass --include-tts to bundle it")

    if args.dry_run:
        for src, dest in items:
            print(f"  {human(src.stat().st_size):>10}  {dest}")
        return

    free = shutil.disk_usage(ROOT).free
    if free < total * (2 if args.archive else 1) + 256 * 1024 * 1024:
        sys.exit(f"not enough free disk: {human(free)} available, need roughly "
                 f"{human(total * (2 if args.archive else 1))} plus headroom")

    if args.out.exists():
        shutil.rmtree(args.out)
    args.out.mkdir(parents=True)

    digests: list[tuple[str, str]] = []
    for src, dest in items:
        target = args.out / dest
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, target)
        digests.append((sha256(target), dest))

    checksums = args.out / "CHECKSUMS.sha256"
    checksums.write_text("".join(f"{d}  {name}\n" for d, name in sorted(digests, key=lambda x: x[1])),
                         encoding="utf-8")
    print(f"wrote {checksums.relative_to(ROOT)} covering {len(digests)} files")

    if args.archive:
        archive = args.out.with_suffix(".zip")
        with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as z:
            for path in sorted(args.out.rglob("*")):
                if path.is_file():
                    z.write(path, path.relative_to(args.out))
        print(f"wrote {archive.relative_to(ROOT)} ({human(archive.stat().st_size)})")

    print(f"bundle ready at {args.out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
